In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 

C:\ProgramData\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.TXA6YQSD3GCQQC22GEQ54J2UDCXDXHWN.gfortran-win_amd64.dll
C:\ProgramData\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)


## Data Exploration

In [2]:
data = pd.read_csv(r'C:\Users\DELL\udemy recommendation system\2..Movie-lens\Datasets/cleaned_data.csv')

In [3]:
data.head(2)

userId  movieId  rating           title                      genres  \
0       1        2     3.5  Jumanji (1995)  Adventure|Children|Fantasy   
1       5        2     3.0  Jumanji (1995)  Adventure|Children|Fantasy   

   TotalRatingCount  
0               112  
1               112

In [4]:
data['title']

0                   Jumanji (1995)
1                   Jumanji (1995)
2                   Jumanji (1995)
3                   Jumanji (1995)
4                   Jumanji (1995)
                   ...            
99995    He Walked by Night (1948)
99996      Lone Ranger, The (1956)
99997      Gardens of Stone (1987)
99998            Field, The (1990)
99999              Fired Up (2009)
Name: title, Length: 100000, dtype: object

In [6]:
#the 'set' removes alll the duplicate values from our data 
len(set(data['title']))

8225

## Building a pivot table 

In [7]:
data.columns

Index(['userId', 'movieId', 'rating', 'title', 'genres', 'TotalRatingCount'], dtype='object')

In [12]:
pivot_table = data.pivot_table(index='title', columns='userId', values= 'rating').fillna(0)

In [14]:
pivot_table.shape

(8225, 702)

In [15]:
from scipy.sparse import csr_matrix

In [17]:
#this converts our dataframe into an array allow us use it in our csr_matrix
pivot_table.values

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
features_matrix = csr_matrix(pivot_table.values)

In [20]:
# a sparse matrix is a matrix that has very few non-zero values 

In [19]:
features_matrix

<8225x702 sparse matrix of type '<class 'numpy.float64'>'
	with 99997 stored elements in Compressed Sparse Row format>

## KNN based colarborative model 

In [21]:
from sklearn.neighbors import NearestNeighbors

In [23]:
model = NearestNeighbors(metric='cosine', algorithm='brute', )

In [24]:
model.fit(features_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [25]:
pivot_table.shape

(8225, 702)

In [33]:
query_index = np.random.choice(pivot_table.shape[0])

In [34]:
query_index

5327

In [35]:
query_ind = np.random.choice(pivot_table.shape[1])

In [36]:
query_ind

79

In [42]:
pivot_table.iloc[5327,:].values.reshape(1,-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [47]:
distances

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
distances,indices = model.kneighbors(pivot_table.iloc[query_index,:].values.reshape(1,-1),n_neighbors=8)

In [49]:
distances

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
#using dummy query index
distances,indices = model.kneighbors(pivot_table.iloc[4209,:].values.reshape(1,-1),n_neighbors=8)

In [53]:
distances

array([[0.        , 0.42469558, 0.47014058, 0.47615116, 0.49020388,
        0.49020388, 0.50598491, 0.50847912]])

In [54]:
indices.flatten()

array([4209, 1829, 5108, 2978, 2751, 1074, 7706, 1990], dtype=int64)

### Making our recommendation user friendly

In [55]:
pivot_table.index[4209]

'Last Temptation of Christ, The (1988)'

In [57]:
pivot_table.iloc[indices.flatten()]

userId                                 1    2    3    4    5    6    7    8    \
title                                                                           
Last Temptation of Christ, The (1988)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Dangerous Liaisons (1988)              0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
My Man Godfrey (1957)                  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Go Fish (1994)                         0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Frankie Starlight (1995)               0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Bound for Glory (1976)                 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Up at the Villa (2000)                 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
Desert Bloom (1986)                    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                                 9    10   ...  693  694  695  696  697  \
title                                            ...                            
Last Temptation of Christ, The (1988)  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Dangerous Liaisons (1988)              0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
My Man Godfrey (1957)                  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Go Fish (1994)                         0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Frankie Starlight (1995)               0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Bound for Glory (1976)                 0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Up at the Villa (2000)                 0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   
Desert Bloom (1986)                    0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0   

userId                                 698  699  700  701  702  
title                                                           
Last Temptation of Christ, The (1988)  0.0  0.0  0.0  0.0  0.0  
Dangerous Liaisons (1988)              0.0  0.0  0.0  0.0  0.0  
My Man Godfrey (1957)                  0.0  0.0  0.0  0.0  0.0  
Go Fish (1994)                         0.0  0.0  0.0  0.0  0.0  
Frankie Starlight (1995)               0.0  0.0  0.0  0.0  0.0  
Bound for Glory (1976)                 0.0  0.0  0.0  0.0  0.0  
Up at the Villa (2000)                 0.0  0.0  0.0  0.0  0.0  
Desert Bloom (1986)                    0.0  0.0  0.0  0.0  0.0  

[8 rows x 702 columns]

In [58]:
distances.flatten()

array([0.        , 0.42469558, 0.47014058, 0.47615116, 0.49020388,
       0.49020388, 0.50598491, 0.50847912])

In [60]:
pivot_table.index[indices.flatten()][2]

'My Man Godfrey (1957)'

In [67]:
for i in range(0, len(distances.flatten())):
    if i ==0:
        print('Recommendation for {0}'.format(pivot_table.index[query_index]))
        
    else:
        print('{} : {}, with a distance of {}'.format(i, pivot_table.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendation for Notorious Bettie Page, The (2005)
1 : Dangerous Liaisons (1988), with a distance of 0.42469557924062284
2 : My Man Godfrey (1957), with a distance of 0.4701405762384343
3 : Go Fish (1994), with a distance of 0.4761511584720963
4 : Frankie Starlight (1995), with a distance of 0.49020387768154294
5 : Bound for Glory (1976), with a distance of 0.49020387768154294
6 : Up at the Villa (2000), with a distance of 0.5059849059839756
7 : Desert Bloom (1986), with a distance of 0.5084791232370767
